name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: event-pro-473112
  GCP_REGION: asia-southeast1
  AR_REPO: eventpro-repo
  SERVICE_NAME: eventpro-backend

  IMAGE: asia-southeast1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (workload identity)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/446938054709/locations/global/workloadIdentityPools/github/providers/github-oidc
          service_account: github-actions-deployer@event-pro-473112.iam.gserviceaccount.com
          token_format: access_token

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build -t "${IMAGE}" .

      - name: Push image to Artifact Registry
        run: |
          docker push "${IMAGE}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --project ${{ env.GCP_PROJECT_ID }} \
            --region ${{ env.GCP_REGION }} \
            --image "${IMAGE}" \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
