name: Deploy Backend to GCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # ---- GCP / service config ----
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}          
  REGION: asia-southeast1                                # Cloud Run region
  GAR_LOCATION: asia-southeast1                          # Artifact Registry location
  REPOSITORY_NAME: eventpro-repo                         # your Artifact Registry repo
  SERVICE_NAME: eventpro-backend                         # Cloud Run service name

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Keyless auth via Workload Identity Federation ---
      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker "${GAR_LOCATION}-docker.pkg.dev" --quiet

      - name: Compute image name
        run: |
          echo "IMAGE=${GAR_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${REPOSITORY_NAME}/${SERVICE_NAME}:${GITHUB_SHA}" >> "$GITHUB_ENV"

      # Build & push container (publish w/o analyzers to unblock CI)
      - name: Build and Push Docker image
        run: |
          docker build -t "$IMAGE" \
            --build-arg BUILDKIT_INLINE_CACHE=1 .
          docker push "$IMAGE"

      # Deploy to Cloud Run and inject GCP Secret Manager values as env vars
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --project "$GCP_PROJECT_ID" \
            --region "$REGION" \
            --platform managed \
            --image "$IMAGE" \
            --port 8080 \
            --set-secrets=ConnectionStrings__DefaultConnection=eventpro-db-connection-string:latest \
            --set-secrets=JwtSettings__Key=eventpro-jwt-key:latest \
            --set-secrets=GoogleAi__ApiKey=eventpro-google-ai-key:latest \
            --quiet
          # add --allow-unauthenticated if your service is public

      - name: Show service URL
        run: |
          URL="$(gcloud run services describe "$SERVICE_NAME" \
                --project "$GCP_PROJECT_ID" --region "$REGION" \
                --format='value(status.url)')"
          echo "Cloud Run URL: $URL"
